apiVersion: v1
kind: ConfigMap
metadata:
  name: copilot-api-config
  namespace: staging
  labels:
    app: copilot-api
    env: staging
data:
  NODE_ENV: "production"
  PORT: "3000"
  HOST: "0.0.0.0"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  MANUAL_APPROVE: "false"
  SHOW_TOKEN: "false"
  ENABLE_METRICS: "true"
  ENABLE_HEALTH_CHECKS: "true"
  ENABLE_VALIDATION: "true"
  ENABLE_RATE_LIMITING: "true"
  ENABLE_GRACEFUL_SHUTDOWN: "true"
  RATE_LIMIT_SECONDS: "0.5"
  RATE_LIMIT_WAIT: "false"
  MAX_REQUEST_SIZE: "10MB"
  REQUEST_TIMEOUT: "30000"
  KEEPALIVE_TIMEOUT: "5000"
  METRICS_ENDPOINT: "/metrics"
  HEALTH_ENDPOINT: "/health"

---
apiVersion: v1
kind: Secret
metadata:
  name: copilot-api-secrets
  namespace: staging
  labels:
    app: copilot-api
    env: staging
type: Opaque
data:
  # Base64 encoded GitHub token for staging - replace with actual value
  GITHUB_TOKEN: Z2hwX3lvdXJfc3RhZ2luZ190b2tlbl9oZXJl

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: copilot-api
  namespace: staging
  labels:
    app: copilot-api
    env: staging
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: copilot-api
      env: staging
  template:
    metadata:
      labels:
        app: copilot-api
        env: staging
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: copilot-api
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: copilot-api
        image: copilot-api:staging
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: copilot-api-secrets
              key: GITHUB_TOKEN
        envFrom:
        - configMapRef:
            name: copilot-api-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 12
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/.cache
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      terminationGracePeriodSeconds: 60
      nodeSelector:
        kubernetes.io/os: linux

---
apiVersion: v1
kind: Service
metadata:
  name: copilot-api
  namespace: staging
  labels:
    app: copilot-api
    env: staging
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: copilot-api
    env: staging

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: copilot-api
  namespace: staging
  labels:
    app: copilot-api
    env: staging

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: copilot-api-network-policy
  namespace: staging
spec:
  podSelector:
    matchLabels:
      app: copilot-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - namespaceSelector:
        matchLabels:
          name: staging
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 443  # HTTPS for GitHub API
    - protocol: TCP
      port: 53   # DNS
    - protocol: UDP
      port: 53   # DNS

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: copilot-api-hpa
  namespace: staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: copilot-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85